package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Step2_ID'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Step2_ID")) {
    check(buildNumberPattern == "%build.counter%") {
        "Unexpected option value: buildNumberPattern = $buildNumberPattern"
    }
    buildNumberPattern = "%dep.SampleBuild_Step1_ID.build.number%"

    triggers {
        add {
            finishBuildTrigger {
                buildType = "SampleBuild_Step1_ID"
                successfulOnly = true
            }
        }
    }

    dependencies {
        expect(RelativeId("Step1_ID")) {
            snapshot {
            }
        }
        update(RelativeId("Step1_ID")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

    }
}
